name: sentinel-env # The name of your conda environment
channels:
  - conda-forge
  - defaults
dependencies:
  # --- Core Python ---
  - python=3.13

  # --- Your Project's PIP Dependencies ---
  # Conda will use pip to install these
  - pip:
    - fastapi
    - redis
    - pydantic
    - feedparser
    - psutil
